language: node_js

node_js:
  - 14

branches:
  only:
  - master

script:
  - cd $TRAVIS_BUILD_DIR/client && npm ci && npm run lint && npm run test
  - cd $TRAVIS_BUILD_DIR/server && npm ci && npm run lint && npm run test